# Generated by Django 5.1.1 on 2024-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
